update deep el vre assumption switch to match current data, and also …
remindmodel/remind pull request #1372
Opened 2023-08-03 08:48 UTC by cchrisgong

…print a more helpful error message

## Purpose of this PR

## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [X ] Bug fix 

## Checklist:

- [ X] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ X] I performed a self-review of my own code
- [ X] I explained my changes within the PR, particularly in hard-to-understand areas
- [ X] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ X] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ X] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ X] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [ X] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

2023-08-03 08:51 UTC, cchrisgong commented
tagging @PhilippVerpoort in case deep el stuff

2023-08-03 08:53 UTC, cchrisgong commented
@robertpietzcker @fschreyer do you know why under deep El switch cm_VRE_supply_assumptions = 1, incolearn is not modified, but under =2 and =3 they are? I thought from reading main.gms, that the floor costs of spv are supposed to be changed under all switch values. Thanks!

2023-08-07 08:39 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes

2023-08-07 08:39 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on core/datainput.gms
> +    fm_dataglob("incolearn","storspv") = 4040;
The whole point of these checks is to ensure that ad-hoc modifications done via some so black Excel magic by @FalkoUeckerdt are not applied to data they were not based on.
This change just takes new, updated data, and declares those changes valid.  Unless Falko green-lights them or provides updated modifications, this cannot be merged.

2023-09-04 14:02 UTC, cchrisgong commented
@LaviniaBaumstark I tried to update the deepEl scenario csv, but my budget runs keep on failing because the cost data (before deepEl modifications) are outdated, in current REMIND version they are lower than they used to be when these deep El switches were implemented..

As you see here, I was trying to submit a bug fix a month ago, but Michaja complained about the format of the change (my bug fix would have created new links between new cost data and some extrapolated cost data based on new cost data and the ratio of the cost decline caused by deep El switch on)

I would like to fix this bug before I upload the new DeepEl csv

@gunnar-pik

2023-09-04 14:57 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
I was not "complaining about the format" of your change.  I was questioning its content.

> my bug fix would have created new links between new cost data and some extrapolated cost data based on new cost data and the ratio of the cost decline caused by deep El switch on

To my understanding, @FalkoUeckerdt's process back then [was more involved](https://mattermost.pik-potsdam.de/rd3/pl/cyb16pjze3f95br7ue93icrw5e) than saying "well, 84 % of `inco0` and 74 % of `incolearn`.
So either get the OK from him that these numbers do check out, get new numbers from him, or get his process/Excel sheet and calculate the numbers.

P.S. I very much doubt that Gunnar receives Github notifications.  So if you want him to look at this, better send him a message.

2023-09-19 20:22 UTC, FalkoUeckerdt commented
I would keep the original deepEl parameters (we were sufficiently optimistic 2 years ago), even though our default assumptions got more optimistic. I would thus suggest to not implement the deepEl numbers in relation or dependent on other (default) parameters, but as absolute values.

2023-10-11 09:37 UTC, cchrisgong commented
hi, thanks both, I'm just back from vacation - will work on this this week @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q

2023-10-12 09:33 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q approved these changes

2023-10-12 10:37 UTC, merged