delete realization 36_buildings/services_putty and 36_buildings/services_with_capital
remindmodel/remind pull request #1509
Opened 2023-12-18 10:28 UTC by LaviniaBaumstark

## Purpose of this PR
cleaning up REMiND: 
delete old realizations 36_buildings/services_putty and 36_buildings/services_with_capital and all releated code in 29_CESparameters/calibrate

## Type of change

- [x] Refactoring

## Checklist:

- [] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [ ] I explained my changes within the PR, particularly in hard-to-understand areas
- [ ] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ ] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ ] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ ] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [ ] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

## Further information (optional):

* Test runs are here: 
* Comparison of results (what changes by this PR?):

2024-02-01 14:38 UTC, LaviniaBaumstark commented on modules/29_CES_parameters/calibrate/preloop.gms
> -);
I will add it

2024-02-05 12:46 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
>        )
Fix indentation.

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
>          );
Fix indentation.

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
> +         pm_cesdata(t,regi,"inco","quantity"), " -> ";
Fix indentation.

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
> +    put pm_cesdata(t,regi,in,"price") /;
Fix indentation.

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
>          )
What's with the brackets?

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
>            )
What's with the brackets?

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
>        );
Fix indentation.

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
> +         );
Fix indentation.

2024-02-05 13:14 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
> +       put sm_CES_calibration_iteration:0:0, "remind" , t.tl, in2.tl  , "quantity", regi.tl, ( pm_cesdata(t,regi,in2,"quantity") ) /;
What's with the brackets?

2024-02-05 13:27 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes
https://github.com/remindmodel/remind/pull/1509/files#diff-54a5960804a16adc77b7ddc96e32be89e442abbd1f89b0fa5cd8e7c5a1b174b7R714

Probably some years-old merge leftover, but that comment should go, too.

2024-02-05 13:37 UTC, LaviniaBaumstark commented on modules/29_CES_parameters/calibrate/preloop.gms
>            )
closing the log

2024-02-05 13:46 UTC, LaviniaBaumstark commented
> https://github.com/remindmodel/remind/pull/1509/files#diff-54a5960804a16adc77b7ddc96e32be89e442abbd1f89b0fa5cd8e7c5a1b174b7R714
> 
> Probably some years-old merge leftover, but that comment should go, too.

I added teh comment, what do you mean?

2024-02-05 13:54 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
>        )
Close enough.

2024-02-05 14:02 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
> +    );
Is it so difficult to properly indent code?

2024-02-05 14:05 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
https://github.com/remindmodel/remind/blob/5c197bd42b7f4fc66f1bc9073896f632ea656f8a/modules/29_CES_parameters/calibrate/preloop.gms#L992

2024-02-06 09:28 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
> +    put pm_cesdata(t,regi,in,"price") /;
> * Use indentations to make the structure more readable

[[↑]](https://github.com/remindmodel/remind/blob/5c197bd42b7f4fc66f1bc9073896f632ea656f8a/main.gms#L144)

Why is the assignment not indented with the thing being assigned to?

2024-02-06 09:28 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
>          )
Still useless brackets.

2024-02-06 09:28 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented on modules/29_CES_parameters/calibrate/preloop.gms
> +    );
> * Use indentations to make the structure more readable

[[↑]](https://github.com/remindmodel/remind/blob/5c197bd42b7f4fc66f1bc9073896f632ea656f8a/main.gms#L144)

`cesOut2cesIn` is part of the summation index, hence indented with `t` inside the indexing bracket.
The rest is the summation term, hence indented two spaces from `sum`.

2024-02-06 10:50 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q approved these changes

2024-02-06 10:59 UTC, merged