faster make test
remindmodel/remind pull request #1538
Opened 2024-02-01 15:00 UTC by orichters

## Purpose of this PR

- quicker tests
- instead of running a testOneRegi with `action = c`, run `Rscript start.R --gamscompile`. Is somehow much faster (2 min -> 30 seconds)
- don't compile 27 AMT runs, but just a selection of 5 that should cover the modules that are used. Reduces runtime from 12 min to 2 min. Adding a EU21 run is maybe advisable, but also time-consuming as new input data has to be downloaded and distributed twice (before and after the run)
- bit of cleanup in scenario_config descriptions

## Type of change

- [x] Refactoring

## Checklist:

- [x] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [x] I explained my changes within the PR, particularly in hard-to-understand areas
- [x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [ ] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

2024-02-01 15:04 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes
> * Adding a EU21 run is maybe advisable, but also time-consuming as new input data has to be downloaded and distributed twice (before and after the run)

Definitely test `EU21`.  Download times are not an issue on the cluster, people can always test there, or cache locally if they are so inclined.
But changes in regional aggregation are a much more serious source of errors then different module realisations, in my experience.

2024-02-01 15:06 UTC, orichters commented on start_bundle_coupled.R
> -if ("--gamscompile" %in% flags && ! file.exists("input/source_files.log")) {
that is not needed anymore, as `runGamsCompile` does that alone

2024-02-01 15:21 UTC, orichters commented
Something went wrong with the rebase, not fixing it now as #1539 will lead to merge conflicts anyway so that has to be redone anyway.

2024-02-01 15:33 UTC, orichters commented
Ok, including the EU21 run, time is down from ~22 to 14 min.

2024-02-05 08:38 UTC, orichters commented
@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q: Thanks for the comment, I added SSP2EU-EU21-Base to the list of scenarios to be compiled, maybe you can remove "changes requested".

2024-02-05 09:32 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
Sure.  I thought you planned on making a new merge request in order to not deal with the conflicts.

2024-02-05 09:32 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q approved these changes

2024-02-05 09:57 UTC, orichters commented
> Sure. I thought you planned on making a new merge request in order to not deal with the conflicts.

I just wanted to wait for #1536 and #1539 to be merged to avoid fixing the conflicts several times.

2024-02-06 15:10 UTC, LaviniaBaumstark approved these changes

2024-02-06 16:37 UTC, merged