restrict definition of q37_feedstockShares
remindmodel/remind pull request #1599
Opened 2024-03-05 14:02 UTC by mellamoSimon

## Purpose of this PR
restrict the definition of q37_feedstockShares to relevant sets.
With the current fix `testOneRegi` still fails but with infeasibilities instead of  `All Jacobian elements in the row are very small`

## Type of change

- [ ] Bug fix 

## Checklist:

- [ ] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [ ] I performed a self-review of my own code
- [ ] I explained my changes within the PR, particularly in hard-to-understand areas
- [ ] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ ] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ ] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ ] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [ ] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

* Test runs are here: 
`/p/tmp/simonlei/this-is-remind/remind/output/`

2024-03-05 14:02 UTC, mellamoSimon commented
test runs are running in the above mentioned folder

2024-03-05 15:08 UTC, Renato-Rodrigues requested changes
It looks fine so far from the NPi run at: 
`/p/tmp/simonlei/this-is-remind/remind/output/SSP2EU-NPi_2024-03-05_13.38.14`

I would just resolve the conflicts and I would be fine with the merge.

2024-03-05 16:31 UTC, Renato-Rodrigues approved these changes

2024-03-06 07:49 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
@mellamoSimon, do https://github.com/mellamoSimon/remind/pull/8.
What is the purpose of `q37_FossilFeedstock_Base`?

2024-03-06 09:33 UTC, mellamoSimon commented
>What is the purpose of q37_FossilFeedstock_Base?

that was set up by @fschreyer to prevent the model from using biomass or synfuels in baseline runs. However, I think that now that might be unnecessary because we improved emissions accounting (including incineration) and we are not supposed to use `baseline` anymore...

2024-03-06 09:34 UTC, mellamoSimon commented
I'm halting this merge, cause the tests failed for `NPi`

2024-03-06 09:36 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
> I'm halting this merge, cause the tests failed for `NPi`

:point_right: https://github.com/mellamoSimon/remind/pull/8

2024-03-06 09:46 UTC, mellamoSimon commented
I strated new tests in the same folder

2024-03-06 10:32 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q commented
The current REMIND input gdxes are thoroughly broken, so I started a second test with the previous input gdx (`c1256714220e99250f791cc35e61ae51d3bdc7da`) at `/p/tmp/pehl/Remind/output/SSP2EU-NPi_2024-03-06_11.31.54`.

2024-03-07 09:53 UTC, mellamoSimon commented
Quick update as Michaja is out of the office for the rest of this week.  Below is the summary for this run:
>The current REMIND input gdxes are thoroughly broken, so I started a second test with the previous input gdx (c1256714220e99250f791cc35e61ae51d3bdc7da) at /p/tmp/pehl/Remind/output/SSP2EU-NPi_2024-03-06_11.31.54

So I'm not sure if I should merge yet. Maybe a new calibration will fix things but I don't know about the workflow in this case: should we re-calibrate and test first and then merge? Thanks!

```
REMIND run finished!

Model summary:
  gams_runtime is 12.9 hours.
  full.gms exists, so the REMIND GAMS code was generated.
  full.log and full.lst exist, so GAMS did run.
! abort.gdx exists, a file containing the latest data at the point GAMS aborted execution.
  non_optimal.gdx exists, because iteration 69 did not find a locally optimal solution. modelstat: 6 (Intermediate Infeasible)
  fulldata.gdx exists, because iteration 70 was successful. modelstat: 2 (Locally Optimal)
  Modelstat after 70 iterations: 2 (Locally Optimal)
  full.log states: *** Status: Execution error(s)

Infeasibilities extracted from full.lst with nashstat -F:
itr 	 region 	 solvestat            	 modelstat               	 resusd   	 objval           
  6 	 CHA 	    NORMAL COMPLETION 	      LOCALLY INFEASIBLE 	  544.922 	  64.0247890145572 	 F
... 3 infeasibilities omitted, show all with nashstat -a ...
 69 	 MEA 	 TERMINATED BY SOLVER 	 INTERMEDIATE INFEASIBLE 	 1038.762 	 -37173.3285338495 	 F
If infeasibilities appear some iterations before GAMS failed, check nashstat -a carefully.
The error that stopped GAMS is probably not the actual reason to fail.

Failed markets in fulldata.gdx:
 - peoil: 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050 ...
 - pegas: 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050 ...
 - pecoal: 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050 ...
 - good: 2005, 2010, 2015, 2020, 2025, 2030, 2040, 2045, 2050, 2055 ...
No failed tax convergence in fulldata.gdx.
```

2024-03-07 11:14 UTC, Renato-Rodrigues commented
The change in this PR fixes a clear bug that is currently active in the REMIND code. 
I would say that if the changes do not cause pre-triangular issues, and if in the runs all industry equations are limited to the right dimensions, we will be in a better shape to figure out which other issues are holding back the REMIND convergence with this merged than not.
So I would say, go ahead and merge the changes here, as long as the points I raised above have no issue.

2024-03-07 17:03 UTC, mellamoSimon commented
[ FAIL 0 | WARN 0 | SKIP 6 | PASS 80 ] :)

2024-03-07 17:03 UTC, merged