Added import constraints linked to other variables. E.g. coking coal coal import in India.
remindmodel/remind pull request #1804
Opened 2024-08-30 13:38 UTC by nicobauer

## Purpose of this PR

## Type of change

(Make sure to delete from the Type-of-change list the items not relevant to your PR)

- [ ] Bug fix 
- [ ] Refactoring
- [ x] New feature 
- [x ] Minor change (default scenarios show only small differences)
- [ ] Fundamental change
- [ ] This change requires a documentation update

## Checklist:

- [x ] My code follows the [coding etiquette](https://github.com/remindmodel/remind/blob/develop/main.gms#L80)
- [x ] I performed a self-review of my own code
- [x ] I explained my changes within the PR, particularly in hard-to-understand areas
- [ ] I checked that the [in-code documentation](https://github.com/remindmodel/remind/blob/develop/main.gms#L120) is up-to-date
- [ ] I adjusted the reporting in [`remind2`](https://github.com/pik-piam/remind2) where it was needed
- [ ] I adjusted `forbiddenColumnNames` in [readCheckScenarioConfig.R](https://github.com/remindmodel/remind/blob/develop/scripts/start/readCheckScenarioConfig.R) in case the PR leads to deprecated switches
- [ x] All automated model tests pass (`FAIL 0` in the output of `make test`)
- [ ] The changelog `CHANGELOG.md` [has been updated correctly](https://gitlab.pik-potsdam.de/rse/rsewiki/-/wikis/Standards-for-Writing-a-Changelog)

## Further information (optional):

* Test runs are here: /p/projects/remind/users/nicolasb/remind3p2p2_prep/remind-1/output/SSP2-Base_2024-08-30_10.20.07
* Comparison of results (what changes by this PR?):

2024-08-30 14:14 UTC, LaviniaBaumstark requested changes

2024-08-30 14:14 UTC, LaviniaBaumstark commented on modules/24_trade/standard/input/p24_trade_constraints.cs4r
> +*NB* by hand, no mrremind or similar
this file needs to be generated by mrremind. Can be part of the source expert_guess if there is no other source for this information

2024-08-30 14:36 UTC, nicobauer commented
Never did that. No idea. #FormFollowsFunction

2024-09-03 14:20 UTC, nicobauer commented
@LaviniaBaumstark Du sag mal eigentlich müsste dieser PR doch nun akzeptiert sein. Oder?

2024-09-03 14:33 UTC, LaviniaBaumstark commented
still waiting for the new input data :-)

2024-09-05 08:07 UTC, nicobauer commented
@LaviniaBaumstark I can now merge all the changes into  develop. Right? I think you still need to approve the changes in the review process.

2024-09-05 09:10 UTC, LaviniaBaumstark commented
you first need to commit your adjustments to the default.cfg

2024-09-05 14:17 UTC, nicobauer commented
Es ist mir ein Buch mit 7 Siegeln. Ich habe jetzt einen extra PR für die revsions-Nummer gemacht. [Welcher Sadist hat sich nur dieses git-System ausgedacht?]

2024-09-05 14:50 UTC, LaviniaBaumstark commented
it should work as part of this PR, but o.k. merging just back to back is also fine for now.

2024-09-05 14:50 UTC, LaviniaBaumstark approved these changes

2024-09-05 14:56 UTC, merged