delete gdx from repository, input.gdx will be downloaded with the inp…
remindmodel/remind pull request #363
Opened 2021-04-22 18:07 UTC by LaviniaBaumstark

…ut data

2021-04-23 07:41 UTC, giannou approved these changes

2021-04-28 08:44 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes
Any reason in particular `.gitattributes` and `.gitignore` were deleted?

2021-04-28 09:15 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q approved these changes

2021-04-28 09:15 UTC, LaviniaBaumstark commented
sorry, happened by accident, fixed now

2021-04-28 09:19 UTC, merged