Refactor CES markup cost implementation and extent it to industry subsectors
remindmodel/remind pull request #505
Opened 2021-09-21 10:31 UTC by fschreyer

Changes:
* refactor CES markup cost implementation to work with different CES structures in buildings and industry
* extent implementation to industry subsectors realization

Background: 
The CES markup cost serves to have some representation of the cost of end-use technologies in buildings and industry (for example cost of heat pumps, electric arc furnaces etc.). The cost are placed on the bottom-level in ``vm_cesIO`` and can be controled via the switches ``cm_CESMkup_ind`` and ``cm_CESMkup_build``. 

By default, there is currently a markup only on heat pump electricity in buildings (``feelhpb``), district heat (``feheb``) and electricity in fixed_shares industry (``feeli``). In the future, we could extent this to ppfen in industry subsectors like ``feelwlth_otherInd`` or others to represent some end-use transformation cost. In specific policy scenarios, these markup cost might also be lowered to represent policy subsidies in certain sectors/for certain technologies. So currently, nothing changes but I might get back to you on this topic about where/how markups make sense.

2021-09-22 05:44 UTC, rkrekeler approved these changes

2021-09-22 11:55 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q requested changes
```
s37_costAddH2Inv "additional h2 distribution costs for low diffusion levels. [3.25$/kg = 0.1$/kWh]"
```

Square brackets should contain the unit of the scalar.  From this it is not clear whether the number is in \$/kg or \$/kWh.

```
q37_costAddH2PhaseIn(t,regi)..
  v37_costAddTeInvH2(t,regi,"tdh2s")
  =e=
    ( 1 /(
      1 + (3**v37_costExponent(t,regi))
      )
    ) * (
      s37_costAddH2Inv * 8.76
      * ( sum(emiMkt, vm_demFeSector(t,regi,"seh2","feh2s","indst",emiMkt)))
    )
+ (v37_expSlack(t,regi)*1e-8)
```

Reformulate to

```
q37_costAddH2PhaseIn(t,regi)..
  v37_costAddTeInvH2(t,regi,"tdh2s")
  =e=
    (1 / (1 + (3 ** v37_costExponent(t,regi)))) 
  * ( s37_costAddH2Inv 
    * 8.76
    * sum(emiMkt, vm_demFeSector(t,regi,"seh2","feh2s","indst",emiMkt))
    )
  + (v37_expSlack(t,regi) * 1e-8)
;
```

for legibility

- Where does the magic number `8.76` come from?  Couldn't `s37_costAddH2Inv` be in correct units already, since it isn't used anywhere else?
- Same for `1e-8`.  Wouldn't `sm_eps` (1e-9) do, too?

2021-09-23 08:56 UTC, fschreyer commented
Ok, I clarified the use ``s37_costAddH2Inv`` and its unit conversion. This ``q37_costAddH2PhaseIn`` implementation was done by @Renato-Rodrigues. He should intervene in case I misunderstood something.

2021-09-23 11:28 UTC, Renato-Rodrigues commented
If you care about the unit conversion in the equation you can change the s37_costAddH2Inv unit. Just remember to also change the s36_costAddH2Inv scalar the same way.

1e-8 could also be replaced by sm_eps. If you do that, I would recommend doing a test run after the change just for sanity check.

2021-09-23 12:09 UTC, 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q approved these changes

2021-09-24 07:26 UTC, merged